platform :ios, '12.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityFcm', :path => '..\..\node_modules\@capacitor-community\fcm'
  pod 'CapacitorCommunityFirebaseAnalytics', :path => '..\..\node_modules\@capacitor-community\firebase-analytics'
  pod 'CapacitorCommunityFirebaseCrashlytics', :path => '..\..\node_modules\@capacitor-community\firebase-crashlytics'
  pod 'CapacitorApp', :path => '..\..\node_modules\@capacitor\app'
  pod 'CapacitorBrowser', :path => '..\..\node_modules\@capacitor\browser'
  pod 'CapacitorDevice', :path => '..\..\node_modules\@capacitor\device'
  pod 'CapacitorHaptics', :path => '..\..\node_modules\@capacitor\haptics'
  pod 'CapacitorKeyboard', :path => '..\..\node_modules\@capacitor\keyboard'
  pod 'CapacitorNetwork', :path => '..\..\node_modules\@capacitor\network'
  pod 'CapacitorPushNotifications', :path => '..\..\node_modules\@capacitor\push-notifications'
  pod 'CapacitorSplashScreen', :path => '..\..\node_modules\@capacitor\splash-screen'
  pod 'CapacitorStatusBar', :path => '..\..\node_modules\@capacitor\status-bar'
  pod 'CapacitorStorage', :path => '..\..\node_modules\@capacitor\storage'
  pod 'JoinfluxFirebaseRemoteConfig', :path => '..\..\node_modules\@joinflux\firebase-remote-config'
  pod 'ProteansoftwareCapacitorStartNavigation', :path => '..\..\node_modules\@proteansoftware\capacitor-start-navigation'
  pod 'CapacitorCalendar', :path => '..\..\node_modules\capacitor-calendar'
  pod 'CapacitorEmailComposer', :path => '..\..\node_modules\capacitor-email-composer'
  pod 'CapacitorNativeSettings', :path => '..\..\node_modules\capacitor-native-settings'
  pod 'CapacitorRateApp', :path => '..\..\node_modules\capacitor-rate-app'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
