name: Build Android app
on:
  workflow_run:
    workflows: ["Release version"]
    types:
      - completed

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: fastlane android beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
