name: Build iOS app
on:
  workflow_run:
    workflows: ["Release version"]
    types:
      - completed

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Decode Match private key to fetch certificates
        uses: timheuer/base64-to-file@v1
        id: match_private_key_file
        with:
         fileName: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
         encodedString: ${{ secrets.MATCH_GIT_PRIVATE_KEY_FILE_BASE64 }}
      - run: fastlane ios beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
