i: name: 'Bump Version'

on:
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Setup
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v3.0.1
        with:
          REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
          TARGET: ${{ secrets.SSH_STAGING_TARGET }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_STAGING_PRIVATEKEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.SSH_STAGING_HOST }}
          REMOTE_USER: ${{ secrets.SSH_STAGING_USER }}
          REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
          TARGET: ${{ secrets.SSH_STAGING_TARGET }}
      - name: Restarting TabT instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_STAGING_HOST }}
          port: ${{ secrets.SSH_REMOTE_PORT }}
          username: ${{ secrets.SSH_STAGING_USER }}
          key: ${{ secrets.SSH_STAGING_PRIVATEKEY }}
          script: cd ${{ secrets.SSH_STAGING_TARGET }} && pm2 reload tabt-rest-pm2.json --env production
